version: '3'
services:
  web:
    build: .
    ports:
    - 80:3000
    environment:
    - NODE_ENV=production
    - MONGODB=mongodb://mongodb:27017/chat
    - WEBSOCKET_PORT=80
    depends_on:
    - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - db:/data/db
    ports:
        - 27017:27017
    command: mongod
volumes:
  db: